title: Oinam Digital Garden
description: "An informational tit-bit, wiki-ish collection of data, learnings, and observations."

url: ''
baseurl: ''

remote_theme: oinam/oinam-jekyll

oinam:
  title: Oinam
  twitter: oinam
  github: oinam
  website: https://oinam.com
  source: https://github.com/oinam/oinam.fyi

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - netlify.toml
  - README.*
  - vendor/