title: Oinam Digital Garden
email: hi@oinam.com
description: "An informational tit-bit, wiki-ish collection of data, learnings, and observations."
url: ""
baseurl: ""

author:
  title: Oinam
  twitter: oinam
  github: oinam

theme: null
markdown: kramdown
highlighter: rouge
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.md
  - styles.css.map
  - netlify.toml
