title: Oinam Digital Garden
email: oinam@oinam.com
description: >- # this means to ignore newlines until "baseurl:"
  An informational tit-bit, wiki-ish collection of data, learnings, and observations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oinam.fyi"
author: Oinam

twitter: oinam
github: oinam

theme: null
markdown: kramdown
highlighter: rouge
permalink: pretty

# Build settings
# plugins:
#   - jekyll-feed

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.md
  - styles.css.map
  - netlify.toml
