title: Oinam's Notebook
description: 'Tit-bit, wiki-ish, data, learnings, and observations.'

remote_theme: oinam/oinam-jekyll

footer:
  credit: true
  custom: true

footer_custom: 'An ever work-in-progress by <a href="https://oinam.com">Oinam</a> (<a href="https://github.com/oinam/oinam.fyi">Source</a>).'

oinam:
  title: Oinam
  website: https://oinam.com
  source: https://github.com/oinam/oinam.fyi

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

plugins:
  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-titles-from-headings

exclude:
  - .jekyll-cache/
  - .obsidian
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.*