title: Oinam Notes
description: 'Tit-bit, wiki-ish, data, learnings, and observations.'

remote_theme: oinam/oinam-jekyll

footer:
  credit: true
  custom: true

footer_custom: 'An ever work-in-progress by <a href="https://oinam.com">Oinam</a> (<a href="https://github.com/oinam/oinam.fyi">Source</a>).'

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

optional_front_matter:
  remove_originals: true

plugins:
  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-browsersync

exclude:
  - .jekyll-cache/
  - .obsidian
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.*