title: Oinam Digital Garden
description: 'Tit-bit, wiki-ish, data, learnings, and observations.'

remote_theme: oinam/oinam-jekyll

footer:
  credit: false
  custom: true

footer_custom: 'An ever Work-in-Progress effort by <a href="https://oinam.com">Oinam</a> (<a href="https://github.com/oinam/oinam.fyi">Source</a>). Since 2020.'

layout:
  theme: default # default, nord

styles:
  font_family: serif


oinam:
  title: Oinam
  twitter: oinam
  github: oinam
  website: https://oinam.com
  source: https://github.com/oinam/oinam.fyi

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - netlify.toml
  - README.*
  - vendor/